#!/usr/bin/env python
# Filename: Project3-4.py

import re
import boto.dynamodb

conn = boto.connect_dynamodb(aws_access_key_id='',aws_secret_access_key='')

table = conn.get_table('Project3-4')

f= open('/Users/Preston/caltech-256.txt')

regexp = re.compile('(.*),(.*),(.*)')

for line in f.readlines():

    result = regexp.search(line)

    item_data = {

        'Category' : result.group(1),
        'Picture': int(result.group(2)),
        'S3URL': result.group(3)
        
    }
    
    item = table.new_item(attrs=item_data)

    item.put()



     


        
    
